---
- name: Get GPG key
  get_url:
    url: "{{ homebridge_key_location }}"
    dest: "{{ homebridge_keyring }}"
    owner: root
    group: root
    mode: '0644'

- name: Set up homebridge repository
  template:
    src: homebridge.list.j2
    dest: "{{ homebridge_apt_repo }}"
    owner: root
    group: root
    mode: '0644'

- name: Install homebridge
  apt:
    name: homebridge
    state: latest
  when: not homebridge_debug